config/routes.rb
Rails.application.routes.draw do
  resources :orders

  root 'orders#index'

  post '/orders/new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @items = Item.all
    @price_array = Item.pluck(:rate)
    @sum = Item.sum(:rate)
    @count = Item.count(:qty)
    @date = Order.pluck(:order_date)
    @order_date = @date.join(',')
    @temp = Item.where(:received => 1).count()
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.all
    @items = Item.all
    @count = Item.count(:qty)
    @temp = Item.where(:received => 1).count()
    @kit = IMGKit.new(render_to_string(:layout => "orders/new", :layout => false),
                                      width: 300, height: 340)
    img = @kit.to_jpg
    send_data(img, :type => "image/jpeg", :disposition => 'inline')
      return
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @orders = Order.all
    @items = Item.all
    @count = Item.count(:qty)
    @temp = Item.where(:received => 1).count()
    render  :pdf => "Bill" , 
            :template => 'orders/create.pdf.erb', # Excluding ".pdf" extension.
            page_height:  100,
            page_width:   80,
            outline: {  outline:   true}
     
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_no, :order_date, :customer_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_no %><br>
    <%= f.number_field :order_no %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.date_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/create.pdf.erb
<!DOCTYPE html>
<html>
<center>
<h2>Invoice</h2>

<p><% @orders.each do |data| %>
 	<strong>Order No:</strong>
 	<%= data.order_no %>
</p>

<p>
	<strong>Customer Name:</strong>
	<%= data.customer_name %>
</p>

<p>
	<strong><%= "#{@temp}/#{@count}" %></strong>
</p>

<p>
  <strong>Order date:</strong>
  <%= data.order_date %>
</p>

<p>
	<strong>Total:</strong>
	<%= @items.sum(:rate)%>
</p>

<% end %>

</center>
</html>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<center>
<h2><u>Customer Orders</u></h2>
<br><br>
<table>
<caption>Listing Customer Orders</caption>
  <thead>
    <tr>
      <th>Order no</th>
      <th>Order date</th>
      <th>Customer name</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |customer_order| %>
      <tr>
        <td><%= customer_order.order_no %></td>
        <td><%= customer_order.order_date %></td>
        <td><%= customer_order.customer_name %></td>
       </tr>
    <% end %>
  </tbody>
</table>
<br><br>
<table>
<caption>Order Details</caption>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product_name %></td>
        <td><%= item.qty %></td>
        <td><%= item.rate %></td>
        <td><%= item.received %></td>
      </tr>
      <% end %>
  </tbody>
</table>


<br>

<h3><%= "The total amount for current order dated #{@order_date} is #{@sum}" %><br>

<%= "Total Count : #{@count}" %><br>

<%= "Status: #{@temp}/#{@count} " %></h3>

<%= button_to "Print Bill[PDF]", :action => "create", :format => :pdf %><br>

<%= button_to "Print Bill[JPG]", :action => "new", :format => :jpg %>

</center>

app/views/orders/new.jpg.erb
<!DOCTYPE html>
<html>
<center>
<div style="width:290px;height:280px;border:1px solid black;">
<h2>Invoice</h2>
   
<p><% @order.each do |data| %>
 	<strong>Order No:</strong>
 	<%= data.order_no %>
</p>

<p>
	<strong>Customer Name:</strong>
	<%= data.customer_name %>
</p>

<p>
	<strong><%= "#{@temp}/#{@count}" %></strong>
</p>

<p>
  <strong>Order date:</strong>
  <%= data.order_date %>
</p>

<p>
	<strong>Total:</strong>
	<%= @items.sum(:rate)%>
</p>

<% end %>

</center>
</html>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order no:</strong>
  <%= @order.order_no %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>